### ISSUE TITLE
workspace build error 

### ISSUE THREAD

**Issue by waltcow** [caaaption/caaaption#75]
**Describe the bug**

xcode build error 

**To reproduce**
follow the readme  **Getting Started Part**

**Expected behavior**

**Screenshots/video**
<img width="1445" alt="image" src="https://user-images.githubusercontent.com/3941174/235817403-1fda5a74-d1cb-43db-814a-863ccf97c037.png">

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/3941174/235817640-ca57c7a9-9a21-4605-8b2a-729518c3e64b.png">

<img width="1998" alt="image" src="https://user-images.githubusercontent.com/3941174/235817664-0c6b04b0-910a-407e-8a66-48f731788507.png">

**Environment**
 - Device: [e.g. iPhone 12 Pro]
 - OS: [e.g. iOS 14]

**Additional context**
Add any more context about the problem here.

**Comment by tomokisun** [comment]
@waltcow 

Can you pull the latest main branch and check git status to make sure there are no differences?
This is what it should look like when you open the caaaption.xcworkspace.

<img width="275" alt="image" src="https://user-images.githubusercontent.com/28350464/235818057-7e163c80-e323-497a-925e-16f3b05146d6.png">

**Comment by waltcow** [comment]
my local repo is synced with latest main branch, git status show there are no differences @tomokisun 

![image](https://user-images.githubusercontent.com/3941174/235818491-e16b72b3-e054-4260-a51b-922b1bff020d.png)

**Comment by tomokisun** [comment]
@waltcow 
thx!

How about restarting Xcode and opening it again, which should work correctly?

**Comment by waltcow** [comment]
wow, everything works fine after restart xcode, THX @tomokisun
