### ISSUE TITLE
xcode file template install fail

### ISSUE THREAD

**Issue by waltcow** [caaaption/caaaption#77]
**Describe the bug**
xcode file template install fail

**To reproduce**

```make install-template```

**Expected behavior**
Give a clear and concise description of what you expected to happen.

**Screenshots/video**

![image](https://user-images.githubusercontent.com/3941174/235857633-38ad5603-b060-4e2a-ba26-9410f6e92946.png)

If applicable, add screenshots/video to help explain the problem.

**Environment**
 - Device: [e.g. iPhone 12 Pro]
 - OS: [e.g. iOS 14]

**Additional context**
Add any more context about the problem here.

**Comment by waltcow** [comment]
copy file with finder works fine

**Comment by tomokisun** [comment]
@waltcow 
This works by changing the permission so that the Terminal app has access to the "Application".

**Comment by waltcow** [comment]
Maybe readme can be more specific about it

**Comment by tomokisun** [comment]
@waltcow 
Yes, it is.
I would be happy to make a contribution if you would like.
